### ISSUE TITLE
Text Search too heavy? nonsense (i got free code if necessary)

### ISSUE THREAD

**Issue by gabrielesilinic** [barrycarey/RedditRepostSleuth#307]
So, i must admit i have no idea how you @barrycarey implemented the image search, but very cool, anyway, i got a repo [RosettaSearch](/gabrielesilinic/rosettasearch) that was supposed to implement a bunch of different search algorithms as i learned them, spoiler, i don't have time to add new stuff but it doesn't matter for this use case

i am here because i was like: you literally do image search then tell me text search is too heavy? WTF?

anyway, just get the code from the ngrams folder, get the .py file, fine-tune it a bit, copy-paste the license on the top of the file you will import (it's MIT license, top permissive ones, GPL compatible) and you got a quick and dirty way to do text search while getting a ratio of similarity between things, the same algorithm is used by postgresql (very big RDBMS) to do full text searches, it's not 100% precise but very efficient, you could also change n-grams as input size changes or maybe prefer short words as ngrams and split long ones, if you need me i'm here, otherwise have fun

**Comment by barrycarey** [comment]
Thanks for the suggestions I'll mess around with it and see how it works. 

The issue I run into with most options is the scale of it.  At the moment I have around 700 million text posts indexed.  Whatever solution I use needs to be fast enough to search against those 700mil posts between 20k and 35k times an hour to keep up with post ingestion. 

I have a working solution using Gensim that I never deployed due to RAM constraints.  I've since doubled the RAM but haven't had time to implement it.

**Comment by gabrielesilinic** [comment]
Sidenote: i was stupid, while my code can be used to solve the issue the actual solution is a reversed index, which can become a bit big
